
#include "BasicDataType.idl"

struct TimedJointState
{
  Time					tm;
  Time					cmd;
  unsigned short			id;
  sequence<float>			angle;
  sequence<float>			velocity;
  sequence<unsigned long>		servoState;
};

struct TimedJointCommand
{
  Time					tm;
  Time					cmd;
  unsigned short			id;
  sequence<float>			angle;
  unsigned long				collidingPartFlag;
};

